/**
 * First-party, cookieless analytics (CLAUDE.md §13E; privacy policy "Cookieless analytics").
 * Nothing here identifies a person: `visitor_hash` is HMAC(dailySalt, ip + ua) computed in
 * `POST /api/t`; the raw IP is never stored. Raw rows (sessions, pageviews, events) live for
 * 90 days and are deleted by the rollup cron; `analytics_daily_rollup` keeps identifier-free
 * aggregates indefinitely. Tracker endpoint and cron write with the service role.
 */
import {
  bigint,
  boolean,
  date,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";
import { adminAll } from "./_policies";
import { id, timestamps } from "./_shared";

export const DEVICE_TYPES = ["desktop", "mobile", "tablet", "bot"] as const;
export type DeviceType = (typeof DEVICE_TYPES)[number];

/** Acquisition channel derived at ingest from referrer host + UTM (never changes later). */
export const CHANNELS = ["direct", "search", "social", "ai", "campaign", "referral"] as const;
export type Channel = (typeof CHANNELS)[number];

export const analyticsSessions = pgTable(
  "analytics_sessions",
  {
    id: id(),
    /** Daily-rotating salted hash; the only visitor identifier. */
    visitorHash: text("visitor_hash").notNull(),
    /** Session id generated by the tracker (sessionStorage); unique per visitor hash. */
    clientSid: text("client_sid"),
    entryPath: text("entry_path").notNull(),
    exitPath: text("exit_path"),
    referrer: text("referrer"),
    /** Lower-cased host of `referrer` with a leading `www.` removed. */
    referrerHost: text("referrer_host"),
    channel: text("channel").$type<Channel>(),
    utmSource: text("utm_source"),
    utmMedium: text("utm_medium"),
    utmCampaign: text("utm_campaign"),
    utmContent: text("utm_content"),
    utmTerm: text("utm_term"),
    /** ISO 3166-1 alpha-2 from `x-vercel-ip-country`. */
    country: text("country"),
    /** Region / state name from `x-vercel-ip-country-region`. */
    region: text("region"),
    city: text("city"),
    deviceType: text("device_type").$type<DeviceType>(),
    os: text("os"),
    browser: text("browser"),
    screenW: integer("screen_w"),
    screenH: integer("screen_h"),
    /** `navigator.connection.effectiveType` (4g, 3g, …) when the browser exposes it. */
    connection: text("connection"),
    isBot: boolean("is_bot").notNull().default(false),
    pageviewCount: integer("pageview_count").notNull().default(0),
    durationMs: integer("duration_ms").notNull().default(0),
    startedAt: timestamp("started_at", { withTimezone: true, mode: "date" }).notNull().defaultNow(),
    lastSeenAt: timestamp("last_seen_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
    ...timestamps,
  },
  (t) => [
    /** Admin-only; the tracker endpoint writes with the service role. */
    adminAll("analytics_sessions"),
    index("analytics_sessions_visitor_idx").on(t.visitorHash, t.startedAt),
    index("analytics_sessions_started_idx").on(t.startedAt),
    uniqueIndex("analytics_sessions_visitor_sid_uidx").on(t.visitorHash, t.clientSid),
  ],
);

export const analyticsPageviews = pgTable(
  "analytics_pageviews",
  {
    id: id(),
    sessionId: uuid("session_id")
      .notNull()
      .references(() => analyticsSessions.id, { onDelete: "cascade" }),
    /** Per-pageview key generated by the tracker so later scroll/leave beacons update the row. */
    clientKey: text("client_key"),
    path: text("path").notNull(),
    title: text("title"),
    referrer: text("referrer"),
    occurredAt: timestamp("occurred_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
    durationMs: integer("duration_ms"),
    timeOnPageMs: integer("time_on_page_ms"),
    /** 0 | 25 | 50 | 75 | 90 | 100 */
    scrollDepthMax: integer("scroll_depth_max").notNull().default(0),
    isEntry: boolean("is_entry").notNull().default(false),
    isExit: boolean("is_exit").notNull().default(false),
    ...timestamps,
  },
  (t) => [
    adminAll("analytics_pageviews"),
    index("analytics_pageviews_path_idx").on(t.path, t.occurredAt),
    index("analytics_pageviews_session_idx").on(t.sessionId),
    index("analytics_pageviews_occurred_idx").on(t.occurredAt),
    uniqueIndex("analytics_pageviews_session_key_uidx").on(t.sessionId, t.clientKey),
  ],
);

/** The single internal conversion vocabulary (§13D). */
export const ANALYTICS_EVENT_NAMES = [
  "booking_started",
  "booking_step",
  "booking_completed",
  "contact_submitted",
  "whatsapp_clicked",
  "call_clicked",
  "testimonial_submitted",
] as const;
export type AnalyticsEventName = (typeof ANALYTICS_EVENT_NAMES)[number];

/** Behaviour events the tracker records besides conversions (never personal data). */
export const BEHAVIOUR_EVENT_NAMES = [
  "click",
  "rage_click",
  "dead_click",
  "outbound",
  "cta",
  "form_focus",
  "form_blur",
  "form_abandon",
] as const;
export type BehaviourEventName = (typeof BEHAVIOUR_EVENT_NAMES)[number];
export type TrackedEventName = AnalyticsEventName | BehaviourEventName;

export const analyticsEvents = pgTable(
  "analytics_events",
  {
    id: id(),
    sessionId: uuid("session_id").references(() => analyticsSessions.id, { onDelete: "cascade" }),
    name: text("name").$type<TrackedEventName>().notNull(),
    path: text("path").notNull(),
    /** Event-specific properties; never personal data. */
    props: jsonb("props")
      .$type<Record<string, string | number | boolean | null>>()
      .notNull()
      .default({}),
    /** Shared with Meta CAPI / browser pixel for de-duplication. */
    eventId: text("event_id"),
    occurredAt: timestamp("occurred_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
    ...timestamps,
  },
  (t) => [
    adminAll("analytics_events"),
    index("analytics_events_name_idx").on(t.name, t.occurredAt),
    index("analytics_events_path_idx").on(t.path, t.occurredAt),
    uniqueIndex("analytics_events_event_id_uidx").on(t.eventId),
  ],
);

/** Dimensions of the daily rollup. `site` has the single key `all`. */
export const ANALYTICS_DIMS = [
  "site",
  "path",
  "country",
  "region",
  "city",
  "device",
  "os",
  "browser",
  "referrer",
  "source",
  "utm_campaign",
  "screen",
  "connection",
  "event",
  "funnel_step",
  "geo_page",
] as const;
export type AnalyticsDim = (typeof ANALYTICS_DIMS)[number];
export const analyticsDimEnum = pgEnum("analytics_dim", ANALYTICS_DIMS);

/**
 * One row per (day, dimension, key). Session-scoped dimensions (country, device, …) count the
 * sessions carrying that value and everything those sessions did; path-scoped dimensions
 * (path, geo_page) count the pageviews on that path. `region` keys are `CC/Region` and `city`
 * keys `CC/Region/City` so a drill-down never merges namesakes across countries.
 */
export const analyticsDailyRollup = pgTable(
  "analytics_daily_rollup",
  {
    id: id(),
    day: date("day", { mode: "string" }).notNull(),
    dim: analyticsDimEnum("dim").notNull(),
    key: text("key").notNull(),
    pageviews: integer("pageviews").notNull().default(0),
    visitors: integer("visitors").notNull().default(0),
    sessions: integer("sessions").notNull().default(0),
    /** Single-pageview sessions (for path dims: bounced sessions that entered on the path). */
    bounces: integer("bounces").notNull().default(0),
    /** Session duration (session dims) or time on page (path dims), summed. */
    durationMsSum: bigint("duration_ms_sum", { mode: "number" }).notNull().default(0),
    entries: integer("entries").notNull().default(0),
    exits: integer("exits").notNull().default(0),
    scroll25: integer("scroll_25").notNull().default(0),
    scroll50: integer("scroll_50").notNull().default(0),
    scroll75: integer("scroll_75").notNull().default(0),
    scroll90: integer("scroll_90").notNull().default(0),
    scroll100: integer("scroll_100").notNull().default(0),
    /** `{ [eventName]: count }` — conversion names on most dims; the `event` dim also counts behaviour events. */
    conversions: jsonb("conversions")
      .$type<Partial<Record<TrackedEventName, number>>>()
      .notNull()
      .default({}),
    ...timestamps,
  },
  (t) => [
    adminAll("analytics_daily_rollup"),
    uniqueIndex("analytics_daily_rollup_day_dim_key_uidx").on(t.day, t.dim, t.key),
    index("analytics_daily_rollup_dim_day_idx").on(t.dim, t.day),
  ],
);
