/**
 * Seed a realistic, deterministic analytics dataset for the admin dashboard:
 *
 *   pnpm db:seed:analytics            (reads SUPABASE_DB_URL from .env via dotenv)
 *
 * 12 months of daily rollups plus 7 days of raw sessions/pageviews/events, generated by
 * `src/lib/analytics/seed-data.ts` (also used by `pnpm test:analytics` against PGlite).
 * Replaces any analytics rows already present. Never run against production with real data.
 */
import "dotenv/config";
import { closeDb, getDb } from "@/db";
import { seedAnalytics } from "@/lib/analytics/seed-data";
import { listGeoPages } from "@/lib/geo/pages";

async function main() {
  const db = getDb();
  if (!db) {
    console.error("SUPABASE_DB_URL is not set — nothing to seed. Copy .env.example to .env first.");
    process.exit(1);
  }
  const geoPageHrefs = (await listGeoPages()).map((p) => p.href);
  const started = Date.now();
  const result = await seedAnalytics(db, { geoPageHrefs });
  console.log(
    `analytics seed: ${result.days} days, ${result.rollupRows} rollup rows, ` +
      `${result.rawSessions} raw sessions / ${result.rawPageviews} pageviews / ${result.rawEvents} events ` +
      `in ${((Date.now() - started) / 1000).toFixed(1)}s`,
  );
  await closeDb();
}

main().catch(async (error) => {
  console.error(error);
  await closeDb();
  process.exit(1);
});
