CREATE TABLE "analytics_daily_rollup" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"day" date NOT NULL,
	"dim" "analytics_dim" NOT NULL,
	"key" text NOT NULL,
	"pageviews" integer DEFAULT 0 NOT NULL,
	"visitors" integer DEFAULT 0 NOT NULL,
	"sessions" integer DEFAULT 0 NOT NULL,
	"bounces" integer DEFAULT 0 NOT NULL,
	"duration_ms_sum" bigint DEFAULT 0 NOT NULL,
	"entries" integer DEFAULT 0 NOT NULL,
	"exits" integer DEFAULT 0 NOT NULL,
	"scroll_25" integer DEFAULT 0 NOT NULL,
	"scroll_50" integer DEFAULT 0 NOT NULL,
	"scroll_75" integer DEFAULT 0 NOT NULL,
	"scroll_90" integer DEFAULT 0 NOT NULL,
	"scroll_100" integer DEFAULT 0 NOT NULL,
	"conversions" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "analytics_daily_rollup" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE UNIQUE INDEX "analytics_daily_rollup_day_dim_key_uidx" ON "analytics_daily_rollup" USING btree ("day","dim","key");--> statement-breakpoint
CREATE INDEX "analytics_daily_rollup_dim_day_idx" ON "analytics_daily_rollup" USING btree ("dim","day");--> statement-breakpoint
ALTER TABLE "analytics_sessions" DROP COLUMN "first_path";--> statement-breakpoint
CREATE POLICY "analytics_daily_rollup_admin_all" ON "analytics_daily_rollup" AS PERMISSIVE FOR ALL TO "authenticated" USING ((select public.is_admin())) WITH CHECK ((select public.is_admin()));--> statement-breakpoint
-- Hand-written additions: updated_at trigger for the recreated rollup table and policy/column documentation.
drop trigger if exists set_updated_at on public.analytics_daily_rollup;--> statement-breakpoint
create trigger set_updated_at before update on public.analytics_daily_rollup for each row execute function public.set_updated_at();--> statement-breakpoint
comment on policy "analytics_daily_rollup_admin_all" on public.analytics_daily_rollup is 'Admin-only. Identifier-free daily aggregates keyed by (day, dim, key), written by GET /api/cron/analytics-rollup with the service role and kept indefinitely.';--> statement-breakpoint
comment on column public.analytics_sessions.visitor_hash is 'HMAC-SHA256(dailySalt, ip + user agent); the salt rotates every UTC day, so the value cannot be linked across days. The raw IP is never stored.';--> statement-breakpoint
comment on column public.analytics_sessions.client_sid is 'Session id generated by the tracker in sessionStorage; scoped by visitor_hash so another visitor cannot append to it.';--> statement-breakpoint
comment on column public.analytics_pageviews.client_key is 'Per-pageview key from the tracker so the scroll-depth and time-on-page beacons update the same row.';--> statement-breakpoint
comment on table public.analytics_sessions is 'Raw analytics; rows older than 90 days are deleted by the rollup cron (privacy policy: Cookieless analytics).';
